webapp/src/constants/configs.ts, webapp/src/containers/SyncStatus/service.tsx, webapp/src/utils/utility.ts
- Use stats api to get total block count.
=> Update logic to get total block count

.github/workflows/release-builds.yml
- Add steps to remove mac zip file
=> Add steps to remove mac zip file

webapp/src/constants/routespath.ts, webapp/src/containers/WalletPage/components/CreateOrRestoreWalletPage/WalletSyncPage/index.tsx, webapp/src/containers/WalletPage/components/CreateOrRestoreWalletPage/WalletSyncPage/walletSyncPage.module.scss, webapp/src/containers/WalletPage/components/CreateOrRestoreWalletPage/index.tsx, webapp/src/routes/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/translations/languages/fr.json
- Add service to block wallet create/restore until wallet is synced
=> Add service to block wallet create/restore until wallet is synced

.gitignore, webapp/src/components/LiquidityAccordion/LiquidityAccordion.module.scss, webapp/src/components/LiquidityAccordion/index.tsx, webapp/src/components/PairIcon/PairIcon.module.scss, webapp/src/components/PairIcon/index.tsx, webapp/src/components/TokenAvatar/index.tsx, webapp/src/components/swapDropdown/SwapDropdown.module.scss, webapp/src/components/swapDropdown/index.tsx, webapp/src/containers/LiquidityPage/components/AddLiquidity/addLiquidity.module.scss, webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/LiquidityPage/components/AvailablePoolPairsList/AvailablePoolPairList.module.scss, webapp/src/containers/LiquidityPage/components/AvailablePoolPairsList/index.tsx, webapp/src/containers/LiquidityPage/index.tsx, webapp/src/containers/LiquidityPage/liquidity.module.scss, webapp/src/containers/WalletPage/components/CreateWallet/CreateNewWallet/index.tsx, webapp/src/containers/WalletPage/components/CreateWallet/CreateWallet.module.scss, webapp/src/containers/WalletPage/components/CreateWallet/VerifyMnemonic/index.tsx, webapp/src/scss/bootstrap/_buttons.scss
=> Additional lp ui fixes

webapp/src/containers/LiquidityPage/components/RemoveLiquidity/index.tsx, webapp/src/containers/LiquidityPage/components/RemoveLiquidity/removeLiquidity.module.scss, webapp/src/scss/bootstrap/_variables.scss
This is for remove liquidity view.
=> remove liquidity UI fixes

electron-app/src/services/defiprocessmanager.ts, webapp/src/app/App.tsx, webapp/src/containers/PopOver/GeneralReIndexModal/index.tsx, webapp/src/containers/PopOver/reducer.tsx, webapp/src/containers/SettingsPage/components/SettingsTabGeneral/index.tsx, webapp/src/containers/SettingsPage/index.tsx, webapp/src/containers/SettingsPage/saga.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/translations/languages/fr.json
- Added reindex opion in setting
=> Added reindex opion in setting

README.md, package.json, webapp/package.json
Updated the About section of the app and added binary setup instruction in readme
=> About Section update

webapp/src/constants/configs.ts, webapp/src/containers/SwapPage/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/utils/utility.ts
- Add dex explorer link for both networks.
=> Add dex explorer link to app

webapp/.neutrinorc.js, webapp/tsconfig.json
Added TS sourcemaps for easier debugging
=> chore: added ts sourcemaps

package.json, webapp/package.json
This reverts commit af123c650571b27de3f8a3aca319581f862164a8.
=> Revert "chore: changed `npm i` to `npm ci`"

webapp/src/containers/LiquidityPage/components/AddLiquidity/addLiquidity.module.scss, webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/CreateDCT.module.scss, webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/index.tsx, webapp/src/scss/_utility.scss, webapp/src/utils/interfaces.ts, webapp/src/utils/utility.ts
fixed the overlapping issue in Liquidity Page - Dropdown
=> fix: overlapping address in lp, added label in receive address

electron-app/src/constants/app.ts, electron-app/src/services/defiprocessmanager.ts
- Add check for account history reindex required
=> Add account history reindex regex

webapp/src/components/KeyValueLi/ValueLi/index.tsx, webapp/src/components/LiquidityAccordion/index.tsx, webapp/src/components/StatCard/index.tsx, webapp/src/components/TokenCard/WalletTokenCard/index.tsx, webapp/src/components/swapDropdown/index.tsx, webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/LiquidityPage/components/LiquidityInfo/index.tsx, webapp/src/containers/LiquidityPage/components/RemoveLiquidity/index.tsx, webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/WalletPage/components/SendPage/index.tsx
Added number mask (comma separated) on multiple pages.
- Wallet Page
- Liquidity Page
- DEX
=> feat: added number mask for other pages

webapp/src/constants/configs.ts, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
=> Fix: Wallet typo

webapp/src/constants/rpcMethods.ts, webapp/src/containers/WalletPage/components/PaymentRequests/index.tsx, webapp/src/containers/WalletPage/components/ReceivePage/CreateNewAddressPage/index.tsx, webapp/src/containers/WalletPage/components/ReceivePage/PaymentRequestList/index.tsx, webapp/src/containers/WalletPage/service.tsx, webapp/src/utils/rpc-client.ts
- Added setlabel rpc call in Add receive address
=> Added setlabel rpc call in Add receive address

webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
Added translations for Account to UTXOs and Total Value Locked.
=> feat: added german translations

electron-app/src/app.ts
Added async/await for the creation of BrowserWindow
=> fix: async/await for BW issue

webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx
Added tx id on click of View On Pool button
=> fix: view on pool added tx id

webapp/src/components/CustomPagination/index.tsx, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/containers/WalletPage/saga.tsx, webapp/src/containers/WalletPage/service.tsx, webapp/src/utils/rpc-client.ts
- Ticket Link: Cancel request on ummount for account history #238
=> Added cancel request for unmount

webapp/src/app/service.tsx, webapp/src/containers/BlockchainPage/__test__/testData.json, webapp/src/containers/PopOver/__test__/__snapshots__/BackupWalletNotice.test.tsx.snap, webapp/src/containers/RpcConfiguration/saga.ts, webapp/src/containers/WalletPage/__tests__/testData.json, webapp/src/containers/WalletPage/saga.tsx, webapp/src/utils/__tests__/testData.json, webapp/src/utils/__tests__/utility.test.ts, webapp/src/utils/electronLogger.ts
- Fixed some test cases
- Added better logging during start up, especially when returning from node side
=> chore: better logging for errors

webapp/src/containers/WalletPage/service.tsx
If address has enough tokens, don't consolidate other tokens.
=> fix: added validation if address has enough tokens

.github/workflows/dev-builds.yml, .github/workflows/release-builds.yml, electron-app/assets/entitlements.mac.plist, electron-app/assets/notarize.js, package.json
Notarize for Mac OS.
Reference - https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
=> build: app notarize

webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx, webapp/src/utils/interfaces.ts
Display all verified tokens even if amount is zero.
=> feat: display verified tokens

webapp/src/components/ViewOnChain/index.tsx, webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/LiquidityPage/components/RemoveLiquidity/index.tsx, webapp/src/containers/LiquidityPage/reducer.tsx, webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/Footer/index.tsx, webapp/src/containers/TokensPage/components/MintToken/index.tsx, webapp/src/containers/TokensPage/components/TokenInfo/index.tsx, webapp/src/containers/WalletPage/components/SendPage/index.tsx, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/utils/utility.ts
1. Added link to explorer for Transaction Page
2. View on Chain button, added on a couple of places
- Add Liquidity
- Remove Liquidity
- Send Page
- DEX
- Create Token
- Mint Token
=> feat: view on chain and added link in transactions

webapp/src/translations/languages/de.json
Added german translations for sending LP tokens
=> chore: added german translations for LP confirm message

webapp/src/containers/WalletPage/components/ReceivePage/PaymentRequestList/index.tsx, webapp/src/containers/WalletPage/saga.tsx, webapp/src/utils/rpc-client.ts, webapp/src/utils/utility.ts
[ Done ] Warning: Address not saved by seed phrase #270
=> Fix: Warning seed phrase bug

.github/workflows/dev-builds.yml, electron-app/src/app.ts, package-lock.json, package.json, typings/settings.ts, webapp/package-lock.json, webapp/package.json, webapp/src/app/App.tsx, webapp/src/app/update.ipcRenderer.ts, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/PopOver/UpdateProgress/ErrorComponent.tsx, webapp/src/containers/PopOver/__test__/__snapshots__/ErrorComponent.test.tsx.snap, webapp/src/containers/Sidebar/Sidebar.module.scss, webapp/src/containers/Sidebar/index.tsx, webapp/src/containers/WalletPage/__tests__/__snapshots__/PaymentRequests.test.tsx.snap, webapp/src/containers/WalletPage/__tests__/__snapshots__/paymentRequestList.test.tsx.snap, webapp/src/containers/WalletPage/__tests__/__snapshots__/receive.test.tsx.snap, webapp/src/containers/WalletPage/components/Tokens/AddToken/index.tsx, webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx, webapp/src/translations/languages/en.json
1. Added logs on App startup with app version.
2. Added logs on Electron app startup with OS version.
3. Bump app version to 2.1.10
4. Handled update failures
5. Fix issue on DFI balance - Scenario where user is from re-index. Sometimes the balance doesn't update correctly.
6. Added version in Sidebar
7. Updated "payment requests" to "receive addresses"
8. Updated "tokens" to "wallets"
=> fix: add fallback for update issues

webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/WalletPage/components/WalletTxns/index.tsx, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
1. Fix default address in DEX page
2. Update pagination label on Wallet TX (from receive address to transactions)
=> fix: set default receive address and update pagination label

webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/SwapPage/service.tsx
[ **Done** ] DEX: Something went wrong #311
=> Fix: DEX: Something went wrong

electron-app/src/services/defiprocessmanager.ts, electron-app/src/utils.ts
1. Delete peers.dat file during re-index
2. Add a validation on close for Code 0 (successful close) to not throw an error
3. Added additional logs on Start
=> fix: stuck at 0% issue

webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/SwapPage/index.tsx
- Max button does not work properly on DEX page #337
=> Fix: Max button issue

electron-app/src/services/defiprocessmanager.ts, webapp/src/constants/rpcModel.ts, webapp/src/constants/units.ts, webapp/src/containers/WalletPage/service.tsx, webapp/src/utils/__tests__/utility.test.ts, webapp/src/utils/utility.ts
1. Some error logs of users, the app is freezing when the file is missing on start up. I added a catch for it and the app will just re-open a new process.
2. Removal of `gettokenbalances`
=> fix: added catch to silently fail the missing file

webapp/src/constants/rpcModel.ts, webapp/src/containers/SyncStatus/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/SyncStatus/__test__/reducer.test.tsx, webapp/src/containers/SyncStatus/__test__/testData.json, webapp/src/containers/SyncStatus/index.tsx, webapp/src/containers/SyncStatus/reducer.tsx, webapp/src/containers/SyncStatus/saga.tsx, webapp/src/translations/languages/en.json, webapp/src/utils/rpc-client.ts, webapp/src/utils/utility.ts
Three states for Sync Status:
1. Preparing sync - display how many peers connected
2. Synchronizing - No change
3. Synchronized - At block (latest block)
=> feat: sync status message update

webapp/src/utils/utility.ts
Fix for this: https://github.com/DeFiCh/app/issues/393
=> Fix: DEX empty address issue

webapp/src/containers/SyncStatus/index.tsx, webapp/src/containers/SyncStatus/saga.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/utils/electronLogger.ts, webapp/src/utils/rpc-client.ts, webapp/src/utils/utility.ts
1. If there are no peers, display "Looking for peers" message
2. Fix console issue where peers is failing if zero due to minItems (1) required.
=> fix: peers empty display issue

webapp/src/containers/SwapPage/index.tsx
- Update error message to show actual error thrown by defi node.
=> Update error message to show actual error thrown by defi node

webapp/src/containers/LiquidityPage/service.tsx
- Added info logs for remove lp service.
=> Added info logs for remove lp service

electron-app/src/services/defiprocessmanager.ts, webapp/src/containers/PopOver/saga.tsx, webapp/src/containers/WalletPage/components/RestoreWallet/index.tsx, webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx, webapp/src/containers/WalletPage/reducer.tsx, webapp/src/containers/WalletPage/saga.tsx, webapp/src/worker/queue/index.ts
- fix: on restore wallet, amounts are not updated 
- fix: on restore wallet, addresses are not loaded
- fix: on reset wallet, transactions from old wallet are still displayed
- some additional logs
=> fix: restore wallet issues

webapp/src/translations/languages/de.json
* Improved translation strings
=> Fix: DE translations for „Tokens“

electron-app/src/app.ts, electron-app/src/constants/app.ts, electron-app/src/ipc-events/backupAndImportWallet.ts, electron-app/src/mnemonic.ts, electron-app/src/services/defiprocessmanager.ts
```
/app/electron-app/src/app.ts:120:14
ERROR: 120:14  no-console      Calls to 'console.log' are not allowed.
/app/electron-app/src/constants/app.ts:36:3
ERROR: 36:3    comment-format  comment must start with a space
/app/electron-app/src/ipc-events/backupAndImportWallet.ts:13:15
ERROR: 13:15   ban-types       Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like `() => void`.
ERROR: 50:9    no-console      Calls to 'console.log' are not allowed.
/app/electron-app/src/mnemonic.ts:5:17
ERROR: 5:17    no-empty        block is empty
/app/electron-app/src/services/defiprocessmanager.ts:50:9
ERROR: 50:9    comment-format  comment must start with a space
ERROR: 135:18  triple-equals   != should be !==
```
=> Fix: tslint issues

webapp/src/app/rootStore.ts
Look into the cancel token error in console #382
=> Fix cancelToken error

webapp/src/constants/configs.ts, webapp/src/utils/utility.ts
- Updated wallet page detail page icons too.
=> Added LTC icon

webapp/src/components/SwapCard/index.tsx, webapp/src/constants/configs.ts, webapp/src/containers/SwapPage/index.tsx
- Call testpoolswap once every second when on swap page #406
=> Add Call testpool swap every second

webapp/src/components/WalletStatCard/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/WalletPage/__test__/__snapshots__/EncryptWalletModal.test.tsx.snap, webapp/src/utils/utility.ts
- Improve price calculation on DEX #427
=> Improve dex calculation

webapp/src/containers/TokensPage/components/CreateToken/DCTDistribution/AddressList/index.tsx
=> fix: remove errors on token create page

webapp/src/components/CustomPagination/index.tsx, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/containers/WalletPage/reducer.tsx, webapp/src/containers/WalletPage/saga.tsx
- Added transaction list pagination backtrack.
=> Added transaction pagination backtrack

.github/labels.yml, .github/workflows/sync-labels.yml
Labels syncing automation configuration as code, used in conjunction with release drafting and oss-governance-bot.
=> Labels syncing automation

.github/PULL_REQUEST_TEMPLATE.md, .github/governance.yml, .github/workflows/oss-governance-bot.yml
> Speed up issue triaging with automated chat-bot and chat-ops operations. Increased code review agility by moving quality control hierarchy from requirements to educational steps.
Setup oss governance bot to automatically manage PR for community contributions.
For motivation please refer to https://github.com/DeFiCh/oss-governance-bot#oss-governance-bot
- Issue governance will be configured by @izzycsy
=> OSS Governance Bot setup for PR

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Draft release automatically on merge, oss-governance-bot will enforce semantics. oss-governace-bot will be updated to required correct semantic on merge.
=> Release drafting automation

.github/CODEOWNERS
CODEOWNERS was not working as expected, this will likely fix it.
- Likely fix it, not 100% certain.
=> Fix codeowners misconfiguration

electron-app/src/controllers/wallets.ts, electron-app/src/services/defiprocessmanager.ts, electron-app/src/utils.ts, package.json, tsconfig.json, typings/ipcEvents.ts, typings/settings.ts, typings/walletMap.ts, webapp/src/app/service.tsx, webapp/src/containers/PopOver/ReIndexModel/index.tsx, webapp/src/containers/PopOver/__test__/reducer.test.tsx, webapp/src/containers/PopOver/reducer.tsx, webapp/src/containers/WalletPage/saga.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind feature
/kind
- Add a force reindex during these conditions:
1. If node version is null on wallet map (to cater existing app users)
2. If node update is MINOR or MAJOR update.
Fixes #
=> feature: force reindex on node update

package.json
=> Revert "build: update release type to draft"

webapp/src/translations/languages/de.json
/kind fix
German translation for failed blocks
Fixes #
=> fix: german translation for block transaction failed

.github/release-drafter.yml
/kind chore
/request @thedoublejay to review
Removed chore, docs and refactor 'kind' from release notes as it does not concern users.
=> chore, docs, refactor excluded from release 

webapp/src/constants/common.ts
=> fix: remap mempool err to blocks pending

webapp/src/app/service.tsx, webapp/src/containers/PopOver/ReIndexModel/index.tsx, webapp/src/containers/RpcConfiguration/reducer.ts, webapp/src/containers/RpcConfiguration/saga.ts
/kind fix
- Fixes the reindex modal issue on switching wallet
- Might fix the node is disconnected issue as well
Fixes #
Root cause is the state is not consistent with the wallet map
=> fix: set node version with state

webapp/src/containers/MasternodesPage/index.tsx
/kind fix
Temporarily disable masternode creation
Fixes #
=> fix: temporary disable masternodes creation

webapp/webpack/config/devServer.js
/kind chore
Disable opening of browser on build of app
Fixes #
=> chore: disable opening of browser on build

webapp/src/app/update.ipcRenderer.ts
/kind fix
When updating the app, it doesn't wait for the binaries to be properly closed. After installation, the database will be corrupted due to app not properly closed prior to update.
Fixes #
=> fix: wait for binary to close before updating

webapp/src/translations/languages/de.json
/kind feature
Updates on some german translations
Fixes #
=> feat: updated german translations

electron-app/src/services/defiprocessmanager.ts
/kind fix
1. Removed re-index on cpp errors
2. Modified the logic for re-index popup. Now, if there's a node issue it will reindex it but not on close.
Fixes #
=> fix: improve reindex issue occurence

electron-app/src/app.ts, electron-app/src/controllers/wallets.ts, electron-app/src/services/defiprocessmanager.ts
/kind fix
1. If user installs an app after v2.3.0. The app will sync first time. However, on restart the reindex modal will popup. Missing default node version if app is fresh starting from v2.3.0.
2. Another issue is when users deleted their files accidentally, now the app re-creates the missing files.
Fixes #
=> fix: wallet map issues

webapp/src/constants/common.ts
/kind fix
Remap Unable to sign input error message
Fixes #
=> fix: remap unable to sign err message

webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx, webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx, webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
UI: Masternode screen #506
/kind
To improve the master node new UI
UI: Masternode screen #506
Fixes #
=> Fix masternode ui

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
=> chore: bump app 2.3.1 and node to 1.5.1

webapp/src/scss/_layout.scss
Wallet: Filter over the screen when trying to send #505
/kind
Resolve: Wallet: Filter over the screen when trying to send #505
Wallet: Filter over the screen when trying to send #505
Fixes #
=> Fix: Change footer to white

webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind fix
Updated some labels
Fixes #
=> fix: updated labels

webapp/src/translations/languages/en.json
Masternode error msg typo: 20k DFI to 20,000 DFI #511
/kind feature
Masternode error msg typo: 20k DFI to 20,000 DFI #511
Masternode error msg typo: 20k DFI to 20,000 DFI #511
Fixes #
=> Update 20k to 20,000

electron-app/src/controllers/wallets.ts, electron-app/src/services/defiprocessmanager.ts, electron-app/src/utils.ts, typings/walletMap.ts, webapp/src/app/service.tsx
/kind feature
Call -spv_resync on start of app if not yet triggered
Fixes #
=> feat: call spv_resync on start

webapp/src/constants/configs.ts, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
CSV: UI fixes #512
/kind fix
This PR is for the fixes of the CSV export transactions feature.
CSV: UI fixes #512
Fixes #
=> fix CSV-UI

webapp/src/utils/utility.ts
Added BCH Icon in the app.
/kind feature
Start showing an icon for the BCH icon
Added Feature to show BCH icon
Fixes #
=> Add BCH icon

webapp/src/constants/configs.ts, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Sequence in CSV table 1st row:
/kind fix
Sequence in CSV table 1st row for wallet transactions page.
CSV: UI fixes #512
Fixes #
=> Fix/csv UI

electron-app/src/controllers/wallets.ts, electron-app/src/services/defiprocessmanager.ts, typings/ipcEvents.ts, typings/rpcConfig.ts, webapp/src/app/App.scss, webapp/src/app/App.tsx, webapp/src/app/service.tsx, webapp/src/containers/MasternodesPage/__test__/saga.test.tsx, webapp/src/containers/MasternodesPage/__test__/service.test.tsx, webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx, webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx, webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx, webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx, webapp/src/containers/MasternodesPage/index.tsx, webapp/src/containers/MasternodesPage/masterNodeInterface.ts, webapp/src/containers/MasternodesPage/reducer.ts, webapp/src/containers/MasternodesPage/saga.tsx, webapp/src/containers/MasternodesPage/service.tsx, webapp/src/containers/PopOver/MasternodeUpdateRestartModal/index.tsx, webapp/src/containers/PopOver/reducer.ts, webapp/src/containers/PopOver/types.ts, webapp/src/containers/RpcConfiguration/reducer.ts, webapp/src/containers/RpcConfiguration/saga.ts, webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx, webapp/src/containers/Sidebar/index.tsx, webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind feature
Currently, we don't have a way to enable/disable a masternode. There are some issues where masternode is created but not on config. Now, we can enable/disable it to ensure that the masternode is in config and running well. Take note that enabling/disabling a masternode will require a node restart as it will re-apply the changes in the config.
Fixes #
=> feat: enable/disable masternode

webapp/src/translations/languages/de.json
=> chore: update translations

webapp/src/constants/configs.ts, webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/translations/languages/en.json, webapp/src/utils/isElectron.ts, webapp/src/utils/utility.ts
/kind fix
fixes for masternode settings update, BCH icon, remove liquidity arrow
Fixes #
=> fix: masternode settings update, BCH icon, remove liquidity arrow

electron-app/src/services/dialogmanager.ts, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/walletDropdown/WalletDropdown.module.scss, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
=> fix: default path for wallet, bump app version to v2.3.2

.github/workflows/dev-builds.yml, package.json
=> feat: select custom installation directory for Windows

webapp/src/translations/languages/en.json
The text used until now is no longer up to date. Therefore I have replaced the text. 
https://github.com/DeFiCh/app/issues/649
@izzycsy @thedoublejay
=> Switch from mnemonic phrase to Wallet Backup

webapp/src/translations/languages/de.json
/kind fix
Update german translations for exit wallet
Fixes #
=> chore: update german translations

electron-app/src/services/uiconfig.ts, electron-app/src/utils.ts
/kind fix
Updated formatting of rpcauth to use user and password
Fixes #
=> fix: config issue

electron-app/src/controllers/wallets.ts
/kind fix
Default wallet is replaced on exit wallet
Fixes #
=> fix: restore wallet issue

.github/workflows/release-builds.yml
/kind chore
Fixes checksum generation
Fixes #
=> fix: release asset updates

webapp/src/translations/languages/de.json
/kind fix
Update german translations on masternode page
Fixes #
=> chore: update translation

webapp/src/containers/HelpPage/index.tsx, webapp/src/containers/PopOver/BackupWalletWarningModel/index.tsx, webapp/src/containers/SettingsPage/components/SettingsTabHeader/SettingsTabHeader.module.scss, webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx, webapp/src/scss/_layout.scss, webapp/src/translations/languages/en.json
/kind fix
1. Fix UI overlay on loaders
2. Remove green border on settings page
Fixes #
=> fix: ui updates

package.json
/kind fix
Bump node version to 1.6.0
Fixes #
=> chore: bump node version to 1.6.0

electron-app/src/controllers/wallets.ts, electron-app/src/services/defiprocessmanager.ts
/kind fix
1. Reverted fix for this issue - https://github.com/DeFiCh/app/pull/665
2. Disabled node checking 
Fixes #
=> fix: remove node validation and fix for exit wallet

webapp/src/containers/ConsolePage/ConsoleComponent/console.scss
/kind fix
- Fix cursor jumping on spaces 
https://github.com/cakedefi/defichain-private/issues/293
Fixes #
=> Fix/cursor jumps before & after {}

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
=> feature: bump app to v2.3.3 and node to v1.6.1

typings/snapshot.ts
/kind feature
Updated snapshot block to 746484
Fixes #
=> chore: updated block to 746484

package.json, webapp/package.json
/kind chore
Bump to 2.3.3 rc 1
Fixes #
=> chore: bump to rc 1

webapp/src/constants/configs.ts, webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Fix: CSV modal showing error
/kind fix
Fixed showing error in CSV modal on entering wrong value
Feat | Wallet: CSV Transaction Export #474
Fixes #
=> fix : Exceed limit in csv

webapp/src/containers/WalletPage/components/SendPage/index.tsx
=> Revert "Fix/Send page max amount logic"

electron-app/src/constants/dirpath.ts, electron-app/src/controllers/snapshot.ts, electron-app/src/utils.ts, package-lock.json, package.json, typings/ipcEvents.ts, webapp/package-lock.json, webapp/package.json, webapp/src/app/snapshot.ipcRenderer.ts, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind feat
Add error if disk space is not enough for snapshot
Fixes #
=> feat: add error block if space is not enough

package.json
/kind feature
Bump node to 1.6.2
Fixes #
=> chore: bump to node 1.6.2

electron-app/src/menus/index.ts, typings/ipcEvents.ts, webapp/src/app/menu.ipcRenderer.ts, webapp/src/containers/SettingsPage/reducer.ts, webapp/src/containers/SettingsPage/saga.tsx
/kind feature
Re-index wallet in menu bar
Fixes #
=> feat: reindex wallet via menu bar

electron-app/src/controllers/snapshot.ts
/kind feature
Removed multiplier and added logs
Fixes #
=> feat: added log and removed multiplier

electron-app/src/controllers/snapshot.ts
=> fix: remove available space validation

.github/workflows/dev-builds.yml, electron-app/src/constants/dirpath.ts, webapp/src/utils/electronLogger.ts
/kind fix
Fixed white screen issue on app with production builds
Fixes #
=> fix: remove deprecated method and white screen issue

electron-app/src/constants/dirpath.ts
/kind fix
Duplicate filepath
Fixes #
=> fix: duplicate path

webapp/src/constants/configs.ts, webapp/src/containers/SwapPage/components/SwapTab/index.tsx, webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/SwapPage/swap.module.scss, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind feature
Add defichain analytics site to DEX page
Fixes #
=> feat: add defichain analytics site to DEX

typings/settings.ts, webapp/package-lock.json, webapp/package.json, webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx, webapp/src/containers/SettingsPage/types.ts, webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx
/kind fix
Updated labels, updated chinese urls for defichain.com
Fixes #
=> fix: labels, defichain.com links

typings/snapshot.ts
/kind feature
Update snapshot to block 831190
Fixes #
=> feat: update snapshot

typings/snapshot.ts
/kind chore
Update snapshot to 835791
Fixes #
=> chore: update snapshot 835791

package-lock.json, package.json, typings/snapshot.ts, webapp/package-lock.json, webapp/package.json, webapp/src/containers/PopOver/UpdateProgress/ErrorComponent.tsx, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap, webapp/src/translations/languages/de.json
/kind chore
Update block to 838093
Fixes #
=> chore: bump to 838093 and update app version to 2.3.4

electron-app/src/services/defiprocessmanager.ts, webapp/src/constants/configs.ts, webapp/src/containers/WalletPage/components/Balances/index.tsx, webapp/src/containers/WalletPage/components/SendPage/index.tsx, webapp/src/containers/WalletPage/spvService.tsx, webapp/src/utils/rpc-client.ts, webapp/src/worker/schedular/updateBalance.ts
/kind feature
Add API for fees. Using https://bitcoinfees.earn.com/api/v1/fees/recommended (fastest fee)
Fixes #
=> feat: add api for fees, disabled spv

electron-app/src/services/defiprocessmanager.ts, package-lock.json, package.json, webapp/package-lock.json, webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/WalletPage/components/Balances/index.tsx, webapp/src/worker/schedular/updateBalance.ts
/kind feature
SPV and update RC version
Fixes #
=> feat: add SPV Wallet

electron-app/src/services/defiprocessmanager.ts, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/WalletPage/components/Balances/index.tsx, webapp/src/worker/schedular/updateBalance.ts
/kind chore
Bump packages and disable SPV
Fixes #
=> chore: bump packages

.github/workflows/dev-builds.yml, electron-app/src/utils.ts, typings/snapshot.ts
/kind fix
Initial install for Mac doesn't open. This PR fixes the missing folder issue.
Fixes #
=> fix: mac issues on initial install

webapp/src/containers/WalletPage/components/Balances/Balances.module.scss, webapp/src/containers/WalletPage/components/Balances/BalancesTokenCard/index.tsx, webapp/src/containers/WalletPage/components/Balances/index.tsx, webapp/src/containers/WalletPage/reducer.ts, webapp/src/containers/WalletPage/service.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
/kind feature
Display UTXO and Token DFI
Fixes #
=> feat: display UTXO and Token DFI

electron-app/src/app.ts, electron-app/src/constants/app.ts
/kind fix
Decrease interval polling. On timeout of processes, it just force closes the app. A fix has been added to force close the processes before closing the wallet.
Fixes #
=> fix: decrease interval of polling, shutdown

electron-app/src/controllers/snapshot.ts
/kind feature
Update index file
Fixes #
=> feat: update index file

package.json, webapp/src/containers/MasternodesPage/masterNodeInterface.ts, webapp/src/containers/MasternodesPage/saga.tsx
/kind chore
Bump node to 1.7.6
Fixes #
=> bump node to 1.7.6

package.json
/kind chore
https://github.com/DeFiCh/ain/releases/tag/v1.7.7
=> Bump ain to v1.7.7

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap, webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap, webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
/kind chore
bump app version to v2.4.5
=> bump app version to v2.4.5

electron-app/src/controllers/snapshot.ts, electron-app/src/menus/index.ts
/kind feature
Download snapshot from Menu
Fixes #
=> download snapshot from menu

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/containers/TransactionsPage/components/SendPage/index.tsx, webapp/src/containers/WalletPage/components/SendPage/index.tsx, webapp/src/utils/utility.ts
=> address validation and bump package

electron-app/src/services/defiprocessmanager.ts, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/containers/WalletPage/components/Balances/index.tsx, webapp/src/worker/schedular/updateBalance.ts
=> enable spv

.github/ISSUE_TEMPLATE/1-bug-report.md
Update of environment parameters checklist.
/kind chore
• Update of environment parameters for future created issues
=> Update bug report env params.md

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
/kind chore
- Update node to 2.2.0.
=> Version 2.7.1 with node 2.2.0

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> bump app and node

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> bump app version

webapp/src/utils/utility.ts
/kind fix
This PR hides the dBURN-DFI pair on DEX tab. This pair was created as part of the fix for the dBTC exploit
Fixes #
=> Hide BURN-DFI pool pair

typings/rpcMethods.ts, webapp/src/utils/rpc-client.ts
/kind feature
Use node `bestblockhash` method directly instead of extracting bestblockhash from `getblockchaininfo`
=> Use node method getbestblockhash

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> chore: bump to 2.6.2 node

webapp/src/translations/languages/de.json
/kind chore
Fixes #
Missing translation, typo
=> chore(translations): updated de.json

webapp/src/components/SlippageTolerance/SlippageTolerance.module.scss, webapp/src/components/SlippageTolerance/index.tsx, webapp/src/constants/configs.ts, webapp/src/containers/SwapPage/__test__/swapTab.test.tsx, webapp/src/containers/SwapPage/components/SwapTab/index.tsx, webapp/src/containers/SwapPage/index.tsx, webapp/src/containers/SwapPage/service.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/translations/languages/fr.json, webapp/src/translations/languages/zhs.json, webapp/src/translations/languages/zht.json, webapp/src/utils/rpc-client.ts
=> feature(core): added slippage tolerance for swap

package.json, webapp/package.json
=> version update for app

webapp/src/containers/SwapPage/reducer.ts
This PR will hide BURN-DFI pair
/kind fix
Fixes #
=> fix(ui-ux): hide BURN-DFI pool pair

webapp/src/translations/languages/fr.json
=> Fix: minor French typos

package-lock.json, package.json, scripts/prebuild.js, webapp/package-lock.json, webapp/package.json
In this Pr we have updated `defid` to version [v4.0.0](https://github.com/DeFiCh/ain/releases/tag/v4.0.0)
/kind chore
Fixes #
=> chore: bump to 4.0.0 node

electron-app/assets/notarize.js, package-lock.json, package.json, webapp/package.json
=> chore(workflow): skip notarize for mac build

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> chore: bump to 4.0.3 node

.github/workflows/dev-builds.yml, .github/workflows/release-builds.yml, electron-app/assets/notarize.js, package-lock.json, package.json
=> chore enable app signing for mac

webapp/src/scss/_layout.scss
=> fix(ui-ux): fixed click functionality on menu items

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> build(deps): updated node version to v4.0.6

webapp/src/scss/_layout.scss
=> fix(ui-ux): enabled click on cancel btn for snapshot download page

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> build(deps): updated node version to v4.0.9

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> bump(node): updated node version to 4.1.0

package.json
=> fix(release) enabled mac-x64-build

.github/workflows/release-builds.yml, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> update(core): added mac universal build and updated release app names

.github/workflows/release-builds.yml, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
Reverts BirthdayResearch/defichain-app#1307
=> Revert "update(core): added mac universal build and updated release app names"

.github/workflows/release-builds.yml, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> update(core): added mac universal build

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json
=> bump(node): updated node version to 4.2.0
