package.json, webapp/package.json
When running _npm init_, it creates a new package-lock.json, updated to _npm ci_ so it will just install packages based on the existing packages.
=> chore: changed `npm i` to `npm ci`

webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/index.tsx, webapp/src/containers/WalletPage/__tests__/services.test.tsx, webapp/src/containers/WalletPage/components/ReceivePage/PaymentRequestList/index.tsx, webapp/src/containers/WalletPage/saga.tsx, webapp/src/containers/WalletPage/service.tsx
There's an issue on _Add Liquidity Page -> Receive Shares At Dropdown_ where we have multiple addresses displayed. I used the addresses in _Wallet Page -> Receive_ as a data source.
=> fix: replaced data source of receiving addresses

webapp/src/components/AddressDropdown/AddressDropdown.module.scss, webapp/src/components/AddressDropdown/index.tsx, webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx, webapp/src/containers/LiquidityPage/components/RemoveLiquidity/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/Footer/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/index.tsx, webapp/src/containers/TokensPage/components/CreateToken/index.tsx, webapp/src/containers/TokensPage/service.tsx, webapp/src/model/address.model.ts
Receive address dropdown is used on multiple pages, _(e.g, Create Token, Add Liquidity, Remove Liquidity)_. I have created a new component _AddressDropdown_ that will be used for all these pages and future pages so logic and style will be same.
=> feat: add AddressDropdown component and updated remove liquidity address

electron-app/src/app.ts, electron-app/src/ipc-events/backupAndImportWallet.ts, electron-app/src/menus/index.ts, webapp/src/app/update.ipcRenderer.ts, webapp/src/containers/RpcConfiguration/saga.ts, webapp/src/containers/WalletPage/saga.tsx
If wallet is not existing, disable the Import, Reset and Backup Wallet.
=> fix: disable menu wallet commands if there is no wallet available

electron-app/src/constants/app.ts, electron-app/src/services/defiprocessmanager.ts
Currently, we have some node syntax errors that breaks the app. Even if you restart, it still returns the same error. I have added a test that if the error is from node side, we will consider it for re-index.
=> fix: re-index on any node syntax errors

package.json, webapp/src/utils/rpc-client.ts
1. Bumped Node to 1.4.2
2. Added parameter `enable_external_dfi_token_tx` to accounttoaccount and sendtokenstoaddress calls
=> chore: bump node version to 1.4.2 and added param

webapp/src/components/TokenCard/DCT/index.tsx
Current result: `Decimal` string has a wrong translation key.
Expected result: `Decimal` string has a correct translation key.
=> Fix: Decimal string at tokens page

webapp/src/containers/WalletPage/components/RestoreWallet/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json
- Current result: `Enter word` placeholder at restore wallet page is not translated
- Expected result: `Enter word` placeholder at restore wallet page is a translated string
=> Fix: Make „Enter word“ placeholder translatable

webapp/src/components/SearchBar/index.tsx, webapp/src/containers/MasternodesPage/index.tsx
- Current result: `searchBar` placeholder is not translated
- Expected result: `searchBar` placeholder is a translated string
=> Fix: i18n output for searchBar placeholder

webapp/src/containers/WalletPage/components/CreateWallet/CreateNewWallet/index.tsx, webapp/src/containers/WalletPage/components/CreateWallet/VerifyMnemonic/index.tsx, webapp/src/scss/_layout.scss
* Align right the `Continue` button
* Align left the `Show me my 24 words again` button
=> Fix: New wallet footer buttons alignment

.github/workflows/dev-builds.yml, .github/workflows/release-builds.yml
Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
[docs.github.com/security-hardening-for-github-actions](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)
[github.blog/collision-detection-on-github-com](https://github.blog/2017-03-20-sha-1-collision-detection-on-github-com/)
* https://github.com/actions/checkout/commits/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
* https://github.com/actions/upload-artifact/commits/e448a9b857ee2131e752b06002bf0e093c65e571
* …
=> Pin github-actions to a full length commit SHA

.github/CODEOWNERS
A CODEOWNERS file to define individuals or teams that are responsible for code in a repository.
=> Added code owners for review requirement and assignment

.github/workflows/dev-builds.yml
Due to increased GH Actions usage, limit CI jobs for dev-builds due to it's long running requests.
- 20 overall maximum concurrency for all jobs in ORG
- 5 for macOS
https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration
=> Run dev-builds only on PR to reduce concurrency cap

webapp/src/containers/WalletPage/components/SendPage/index.tsx, webapp/src/scss/_layout.scss
/kind fix
Fixes visual issues backdrop/overlay behind the footer.
Don't know. Just helping @saurabh391 
The problem I discovered is that `.footer-bar` does not have a `background-color` and thus the `.footer-backdrop` color shows through. Just needed to give `.footer-bar` a color of `$dfi-scent`. I also removed `.sendPage-backdrop` as we don’t need any specificity here.
=> fix footer backdrop

.github/CODEOWNERS, .github/governance.yml, .github/workflows/oss-governance-bot.yml
/kind chore
Upgraded oss-governance-bot to v2 due to workflow automation chaining permission complications. Using a unified bot token now.
https://github.com/DeFiCh/oss-governance-bot/pull/64
=> upgraded oss-governance-bot to v2

electron-app/src/controllers/wallets.ts
/kind fix
If user accidentally deletes all his folders, at the start of the program we are checking wallet_map.json which doesn't exist yet. This fix creates the directory in case this scenario happens.
Fixes #
=> fix: create directory if user accidentally deletes it

webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx, webapp/src/translations/languages/de.json, webapp/src/translations/languages/en.json, webapp/src/translations/languages/fr.json, webapp/src/translations/languages/nl.json, webapp/src/translations/languages/ru.json, webapp/src/translations/languages/zhs.json, webapp/src/translations/languages/zht.json
Added block reward type while showing txns
/kind fix
Will start showing txns for Block rewards
TN Masternode: Rewards not displayed in Wallet #541
Fixes #
=> Added block reward in transaction

.github/CODEOWNERS
/kind chore
Moved CODEOWNERS to individuals instead of teams for better accountability and ownership of specified files.
=> moved codeowners to individuals

webapp/src/utils/rpc-client.ts
/kind fix
Currently, the RPC calls are based on user and password in the URL. This leaves user names and password in clear text and as a part of the url, which is insecure. This changes the config for axios to use the Authorization header which is the recommended way to authorize with JSON RPC APIs.
Additionally, this PR also removes the `cache-control` headers. This is redundant since:
- defid RPC never adds cache control headers to it's responses. So, even in a browser context, this should be unnecessary. 
- Additionally, this can interfere with modern browser sandboxes like CORS and web security.
=> Use Auth header for RPC calls instead of clear text urls

webapp/src/containers/WalletPage/components/Balances/index.tsx
/kind feature
This PR changes the order in which tokens are displayed:
* Primary criterion: Non-zero amounts come first
* Secondary criterion: DST before LP
* Tertiary: hash 
Related to #1035
Fixes #
=> Token sorting: non-zero amounts first

electron-app/src/utils.ts
/kind fix
This PR will move the snapshot folder into ~/.defi/ as opposed to before ~/snapshot
I think this is way more predictable as otherwise this might interfere with other programs on the host system.
Also it exchanges the deprecated rmdirSync() function for rmSync() (see https://nodejs.org/api/deprecations.html#DEP0147 )
- #1072 
I tested the resulting .Appimage file on Arch Linux and everything works as expected.
=> moved snapshot folder into ~/.defi/

.github/workflows/oss-governance-bot.yml, .github/workflows/release-drafter.yml
/kind chore
- Rename workflows related to "OSS Governance" into a single Workflow, renamed the job within to "Labels", "Labeler" and "Bot".
- Add `permissions:` for workflows to harden workflow security.
- Remov the use of `DEFICHAIN_BOT_GITHUB_TOKEN` for security hardening.
- Add `concurrency:` for workflows that requires it.
- Bump versions and migrate "OSS Governance Bot" to use the new org.
=> chore(workflows): cleanup workflow permissions and names

typings/settings.ts
/kind fix
Path link to old folder and app can't check for update. See attached txt-file.
It will automatically inform the user that an update is available - as it has done in the past.
Fixes #
[App-update-path.txt](https://github.com/BirthdayResearch/defichain-app/files/11008044/App-update-path.txt)
=> Update update-path to BirthsdayResearch
